### ISSUE TITLE
Allow connecting to external Syncthing web API

### ISSUE THREAD

**Issue by HybridEidolon** [theCapypara/steamdeck-decky-syncthing#12]
I don't use any of the flatpak solutions, I instead have a custom user systemd unit on my device. So I'm able to load up the proxied web browser from the plugin perfectly fine.

However, I can't access any of the plugin's other functionality without running Syncthing through the plugin itself, which is not what I want to do.

**Comment by theCapypara** [comment]
This is already implemented. Please use the plugin version from the testing store or this Github repo.
