### ISSUE TITLE
Make sure the Flatpak exists error

### ISSUE THREAD

**Issue by oxygala** [theCapypara/steamdeck-decky-syncthing#14]
Hi,

While trying to setup the plugin, the setup screen fails to detect me.kozec.syncthingtk even though it's installed. 

decky-syncthing log says "Start request repeated too quickly" and "Failed with result 'exit-code'"

My Steam version is 3.6.18 and Decky is pre-release.

Thanks

d.

**Comment by mbhargav294** [comment]
Make sure to stop syncthing and quit syncthing gtk desktop application

Added setup instructions to README in this PR: https://github.com/theCapypara/steamdeck-decky-syncthing/pull/15/files

**Comment by oxygala** [comment]
that did the trick, thank you.
