### ISSUE TITLE
Error: TypeError: Failed to fetch, unable to do anything in the plugin

### ISSUE THREAD

**Issue by d-rez** [theCapypara/steamdeck-decky-syncthing#3]
Not sure what happened, it was working fine yesterday, now after rebooting the Deck it can no longer start/stop the service (syncthing-gtk) and / or even display its status properly (always says `TypeError: Failed to fetch`)

I can start SyncThing GTK in game mode and syncthing works fine so it's not a problem with the service itself. That said it seems as if it never even gets to starting the service or checking its status, and if syncthing is already running the plugin is still unable to communicate with it in any way

`last_panic.txt` file has:

```
called `Result::unwrap()` on an `Err` value: SerdeJson(Error("invalid type: string \"8384\", expected u16", line: 1, column: 95))
   0: decky_syncthing_watchdog::panic_util::register_panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:709:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:597:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   5: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   6: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   7: tokio::runtime::scheduler::current_thread::Context::enter
   8: tokio::runtime::context::set_scheduler
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::runtime::Runtime::block_on
  12: decky_syncthing_watchdog::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:20
  16: main
  17: <unknown>
  18: __libc_start_main
  19: _start
             at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
```

but this isn't telling me much. All other log files are not helpful

```
(1)(deck@steamdeck decky-syncthing)$ cat '2023-08-29 02.10.24.log'
[2023-08-29 02:10:24,035][INFO]: Loaded.
[2023-08-29 02:10:24,035][INFO]: Watchdog starting...

(deck@steamdeck decky-syncthing)$ cat watchdog.log  | grep 2:10
2023-08-29T02:10:24.088346822+10:00 INFO::started.

(deck@steamdeck decky-syncthing)$ cat syncthing.log | grep 2:10
(1)(deck@steamdeck decky-syncthing)$
```

Not sure where else to look but it worked for a whole day before it stopped :D Any other places  I could check?

Rebooting Deck, restarting Steam, reloading the plugin, reinstalling plugin, deleting `watchdog.pid` didn't help.

**Comment by miketweaver** [comment]
I had the same error. I fixed it by:
- removing the plugin
- clearing out all the settings:
```
(deck@steamdeck ~)$ rm -rf ~/homebrew/settings/decky-syncthing/
(deck@steamdeck ~)$ rm -rf ~/homebrew/logs/decky-syncthing/
(deck@steamdeck ~)$ rm -rf ~/homebrew/data/decky-syncthing/
```
- reinstalling the plugin

**Comment by d-rez** [comment]
Hmm if that fixed it, it would seem that it's a plugin bug somewhere, happy to keep mine broken for a bit longer if this can help the dev in finding the problem

**Comment by d-rez** [comment]
Found the actual bug, plugin saved the syncthing port to its setting file as string rather than uint_16 which caused the whole thing to break

```
invalid type: string \"8384\", expected u16"
```

Once I manually edited the config json file to make sure port was saved as a number rather than string, plugin started working again. Not sure how the issue happened in the first place.

I.e. problematic config file:

```
{"config_version": 1, "autostart": true, "flatpak_name": "me.kozec.syncthingtk", "port": "8384", "api_key": "<redacted>", "basic_auth_user": "", "basic_auth_pass": "", "keep_running_on_desktop": false}
```

Valid config file:

```
{"config_version": 1, "autostart": true, "flatpak_name": "me.kozec.syncthingtk", "port": 8384, "api_key": "<redacted>", "basic_auth_user": "", "basic_auth_pass": "", "keep_running_on_desktop": false}
```

Imo the plugin should either handle json strings properly alongside integers (throw error if unable to convert) or not allow string to be saved to config file in the first place.

Let's see if I can create a pull request that fixes this issue.

**Comment by theCapypara** [comment]
That is very odd, I didn't run into this issue yet and I don't know what could be causing strings to be written for the port value. I guess maybe (and I haven't looked at the code again) the frontend sends it as text and the Python backend just stores it like that, but it's very weird I haven't run into this during my tests. Very sorry for this!

**Comment by theCapypara** [comment]
In any case if that's the issue, then this error should only happen if you change  the port, and from your description it sounds like you didn't really do anything to cause this, so very odd.

**Comment by theCapypara** [comment]
What would probably be a good idea is to add a custom deserializer to the watchdog (https://github.com/theCapypara/steamdeck-decky-syncthing/blob/main/backend/decky-syncthing-watchdog/src/settings.rs#L32) that falls back to string->int parsing.

**Comment by robbiet480** [comment]
FYI I just experienced this on latest version of decky-loader so its still an issue.

**Comment by RowanSkie** [comment]
Getting this issue. This is weird.

**Comment by theSt33v** [comment]
This issue is not fixed. I had the exact same problem and fixed it in the exact same way today using plugin version 0.1.0-1.

**Comment by theCapypara** [comment]
Please use 0.2.1 instead, 0.1.0-1 is ancient. I am not getting reviews on the new version, so it isn't relased to the stable store.

**Comment by theSt33v** [comment]
> Please use 0.2.1 instead, 0.1.0-1 is ancient. I am not getting reviews on the new version, so it isn't relased to the stable store.

Got it. 0.2.1 works perfectly and the onboarding process is way better. Is there a formal review process that needs to happen before it is released to stable?

**Comment by theCapypara** [comment]
I think it mostly needs people here telling that it works :)
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/557
Thanks!
