### ISSUE TITLE
Allow Using Official Syncthing Binary

### ISSUE THREAD

**Issue by PhasecoreX** [theCapypara/steamdeck-decky-syncthing#7]
Hello!

I am using the official Syncthing binary, located at https://syncthing.net/downloads, the Linux Intel/AMD (64‑bit) variant. I run it with [systemd as an enabled user service](https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service) and everything works nicely in game mode and desktop mode.

By default it's running on port 8384, however for some reason this plugin doesn't want to connect to it. If I select the globe icon in the plugin, it does open the browser to Syncthing, and I can see it working just fine. I've even put the API key in the settings, it still doesn't work.

Wasn't sure if there was something I was doing wrong? I'd assume flatpak or not, the port is the same and so it should still work? Maybe I don't know how this plugin is actually communicating with Syncthing. But regardless I don't need the plugin to manage starting and stopping the binary, I just want it to display the sync information.

Any help would be appreciated!

**Comment by theCapypara** [comment]
Hi! I don't have much time at the moment, but I'm planning to refactor and simplify the plugin a lot, to explicitly allow things such as Flatpak-less Systemd setups for Syncthing. At the moment only Flatpak based setups are supported &  it's hard to say why it wouldn't connect for you.
