### ISSUE TITLE
SyncThing plugin states "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by RowanSkie** [theCapypara/steamdeck-decky-syncthing#9]
After I was able to successfully connect SyncThing one time, I put a GUI account into my SyncThing GTK. Afterward, the plugin now fails to run with said error. It might be the same thing as #3, even though I'd already went to reinstall SyncThing GTK and the plugin a few times.

**Comment by RowanSkie** [comment]
Also, when I try to open SyncThing's page, it leads me to an authentication page despite me having nothing set for the user and password.

**Comment by theCapypara** [comment]
Hi! Have you tried this with the new version of the plugin from the testing store (0.2)?

**Comment by RowanSkie** [comment]
Trying it out. It's better, one thing for sure.
